### ISSUE TITLE
Splitter - IndexError: list index out of range

### ISSUE THREAD

**Issue by dege13** [MoeFwacky/videotools#1]
If I had to guess based on what I am seeing, I would assume that the JSON has less frames in in that would be expected because the last frame in the JSON is lower than the "total frames" in the JSON.

JSON file: [2023-01-06 23-42-51 - Polaroid - 'Annie'.json.zip](https://github.com/MoeFwacky/videotools/files/11233378/2023-01-06.23-42-51.-.Polaroid.-.Annie.json.zip)

Output at command prompt:
```
2023-01-06 23-42-51 - Polaroid - 'Annie'.mkv
683318 TOTAL FRAMES
RGB Threshold value: 18.473789936921303
RGB Threshold adjusted to 21.075886088368165
|████████████████████████████████████████⚠︎ (!) 683317/683318 [100%] in 1.0s (699609.97/s)
Traceback (most recent call last):
  File "c:\videotools\videotools.py", line 206, in <module>
    scenesplitter.processVideo(entry.name, args.directory)
  File "c:\videotools\scenesplitter.py", line 208, in processVideo
    scene_list = getScenes(STATS_FILE,totalFrames,frameRate)
  File "c:\videotools\scenesplitter.py", line 107, in getScenes
    start_frame_data = json_data['frames'][frame]
IndexError: list index out of range
```

End of the JSON file:
 ```
 {
   "f": 683316,
   "ts": "6:19:59.977200",
   "rgb": 18.61812,
   "r": 20.05282,
   "g": 0.22801,
   "b": 196.56265
  }
 ],
 "analysis": {
  "total frames": 683318.0019980021,
  "min_rgb": 0.5525104328703703,
  "max_rgb": 221.84109718865773,
  "median_rgb": 55.421369810763906
 }
}
```

**Comment by dege13** [comment]
I went into getScenes() and I enabled all of the commented print lines for debugging.
Here is the end of the output from that for another file where the error happened:
```
on 582594: FRAME NUMBER 582594 SELECTED, RGB = 11.39047361557055
on 582595: FRAME NUMBER 582595 SELECTED, RGB = 11.33242823434947
on 582596: FRAME NUMBER 582596 SELECTED, RGB = 11.381815608066049
on 582597: FRAME NUMBER 582597 SELECTED, RGB = 11.371457482724303
on 582598: FRAME NUMBER 582598 SELECTED, RGB = 11.358118903890093
on 582599: FRAME NUMBER 582599 SELECTED, RGB = 11.399016182974993
on 582600: FRAME NUMBER 582600 SELECTED, RGB = 11.370523467369269
on 582601: FRAME NUMBER 582601 SELECTED, RGB = 11.364761956920821
on 582602: FRAME NUMBER 582602 SELECTED, RGB = 11.388049373469288
{'scene': 2516, 'start_frame': 582555, 'start_time': '6:44:57.398125', 'end_frame': 582603, 'end_time': '6:44:59.400125'}
|████████████████████████████████████████⚠︎ (!) 582604/582605 [100%] in 1:33.9 (6205.01/s)
Traceback (most recent call last):
  File "c:\videotools\videotools.py", line 206, in <module>
    scenesplitter.processVideo(entry.name, args.directory)
  File "c:\videotools\scenesplitter.py", line 210, in processVideo
    scene_list = getScenes(STATS_FILE,totalFrames,frameRate)
  File "c:\videotools\scenesplitter.py", line 107, in getScenes
    start_frame_data = json_data['frames'][frame]
IndexError: list index out of range
```

TOTAL FRAMES is 582605, we are trying to look at 582604 and it fails.
The JSON file only has up to "f": 582603
Perhaps there is sometimes an issue with detecting the frame data on the last few frames and it never gets written to the JSON file.

**Comment by MoeFwacky** [comment]
I believe this issue to be resolved with the latest update, please re-open this issue if it recurs. A note regarding the frame numbering in the json file. The frame number starts with 0, so the final frame number will always be one less than the actual total number of frames.
