### ISSUE TITLE
videoscanner.py - KeyError: 'audio divisor'

### ISSUE THREAD

**Issue by dege13** [MoeFwacky/videotools#16]
I suspect that the changes to the config.ini for the silence detection were never committed to the project, so I don't know the default value.
audio divisor = ???

```
C:\Users\dege1\Documents\GitHub\vhstools>python videotools.py -sc -d "C:\\vhstools\\1 input"
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::o     o  o      8                 ooooo               8        ::
::8     8         8                   8                 8        ::
::8     8 o8 .oPYo8 .oPYo. .oPYo.     8   .oPYo. .oPYo. 8 .oPYo. ::
::`b   d'  8 8    8 8oooo8 8    8     8   8    8 8    8 8 Yb..   ::
:: `b d'   8 8    8 8.     8    8     8   8    8 8    8 8   'Yb. ::
::  `8'    8 `YooP' `Yooo' `YooP'     8   `YooP' `YooP' 8 `YooP' ::
:::::..::::..:.....::.....::.....:::::..:::.....::.....:..:.....:::
:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
Traceback (most recent call last):
  File "C:\Users\dege1\Documents\GitHub\vhstools\videotools.py", line 727, in <module>
    launch_scanner(directory=args.directory)
  File "C:\Users\dege1\Documents\GitHub\vhstools\videotools.py", line 164, in launch_scanner
    import videoscanner
  File "C:\Users\dege1\Documents\GitHub\vhstools\videoscanner.py", line 37, in <module>
    audio_divisor = int(config['scenesplitter']['audio divisor'])
                        ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\dege1\AppData\Local\Programs\Python\Python311\Lib\configparser.py", line 1273, in __getitem__
    raise KeyError(key)
KeyError: 'audio divisor'
```

**Comment by MoeFwacky** [comment]
This should be handled with the latest update to the config file.
